apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal-test
spec:
  replicas: 1
  selector:
    matchLabels:
      service: portal
  template:
    metadata:
      labels:
        app: portal
        service: portal
    spec:
      containers:
        - name: portal
          image: deploy/portal:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    service: portal
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: portal